driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
    - test::default
  - name: master
    run_list:
    - test::example_master
  - name: slave
    run_list:
    - test::example_slave