driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8081}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - apt::default
  - name: ubuntu-14.04
    run_list:
    - apt::default
  - name: ubuntu-16.04
    run_list:
    - apt::default
  - name: centos-7.2
    run_list:
    - yum-epel::default
    attributes:
      yum:
        epel-testing:
          enabled: true
          managed: true

suites:
  - name: default
    run_list:
    - smokeping::default
    attributes:
      smokeping:
        admin_name: "Admin_Name"
        admin_email: "ExampleAdminEmail@localhost"
        alert_email: "ExampleAlertEmail@localhost"
  - name: master
    run_list:
    - smokeping::example_master
    attributes:
      smokeping:
        master_mode: true
        slave_secret: "read"
        admin_name: "Admin_Name"
        admin_email: "ExampleAdminEmail@localhost"
        alert_email: "ExampleAlertEmail@localhost"
  - name: slave
    run_list:
    - smokeping::example_slave
    attributes:
      smokeping:
        slave_mode: true
